# Generated by Django 5.1 on 2024-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_post_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_link',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
