# Generated by Django 5.1 on 2024-10-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_post_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='crawl_strategies',
            field=models.CharField(choices=[('crawl', 'crawl'), ('rss', 'rss')], default='rss', max_length=200),
            preserve_default=False,
        ),
    ]
